# Generated by Django 2.2.5 on 2019-10-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='childname',
        ),
        migrations.RemoveField(
            model_name='family',
            name='spousename',
        ),
        migrations.AddField(
            model_name='family',
            name='spouseDOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='spouseEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='spouseMobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='spouseNID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='spouseNIDPicture',
            field=models.ImageField(null=True, upload_to='spouse_nid_pic'),
        ),
        migrations.AddField(
            model_name='family',
            name='spouseName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='spousePicture',
            field=models.ImageField(null=True, upload_to='spouse_pic'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.CharField(blank=True, max_length=100, null=True)),
                ('childDOB', models.DateField(null=True)),
                ('childPicture', models.ImageField(null=True, upload_to='spouse_pic')),
                ('Family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.Family')),
            ],
        ),
    ]
