# Generated by Django 2.2.6 on 2019-10-13 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20191004_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='childName',
            new_name='child_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='childDOB',
        ),
        migrations.RemoveField(
            model_name='child',
            name='childPicture',
        ),
        migrations.AddField(
            model_name='child',
            name='child_date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='child_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='child_pic'),
        ),
    ]
