# Generated by Django 2.2.4 on 2019-10-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20191013_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='Family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseNIDPicture',
            new_name='spouse_NID_picture',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseDOB',
            new_name='spouse_date_of_birth',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseEmail',
            new_name='spouse_email',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseMobile',
            new_name='spouse_mobile',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseName',
            new_name='spouse_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spouseNID',
            new_name='spouse_nid',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='spousePicture',
            new_name='spouse_picture',
        ),
    ]
