# Generated by Django 2.2.4 on 2019-10-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20191017_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='spouse_nid',
            new_name='spouse_NID',
        ),
    ]
