# Generated by Django 2.2.5 on 2019-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='no_of_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
